import { OffersDataResponse, ProductChartData } from '../types';
import { analyzeDiscountClient } from './dealAnalyzer';

// Load the pre-aggregated offers data generated by the crawler
export async function fetchOffersData(): Promise<OffersDataResponse> {
  const base = import.meta.env.BASE_URL || './';
  const response = await fetch(`${base}data/offers.json?t=${Date.now()}`);
  if (!response.ok) {
    throw new Error(`خطا در بارگذاری اطلاعات: ${response.status}`);
  }
  return await response.json();
}

// Load individual chart data from static JSON cache
export async function fetchCachedProductChart(productId: number): Promise<ProductChartData | null> {
  try {
    const base = import.meta.env.BASE_URL || './';
    const response = await fetch(`${base}data/charts/${productId}.json`);
    if (response.ok) {
      return await response.json();
    }
  } catch (err) {
    console.warn(`Chart not cached for ${productId}:`, err);
  }
  return null;
}

// Live manual check for ANY product entered by user
export async function fetchLiveProductChart(
  productId: number,
  proxyUrl?: string
): Promise<ProductChartData> {
  // First check if already in static cache
  const cached = await fetchCachedProductChart(productId);
  if (cached) {
    return cached;
  }

  // Attempt live fetching via proxy or direct
  const targetUrl = `https://api.digikala.com/v1/product/${productId}/price-chart/`;
  let fetchUrl = targetUrl;

  if (proxyUrl) {
    fetchUrl = `${proxyUrl.replace(/\/$/, '')}/${encodeURIComponent(targetUrl)}`;
  }

  const res = await fetch(fetchUrl, {
    headers: {
      'Accept': 'application/json',
    },
  });

  if (!res.ok) {
    throw new Error(`خطا در استعلام چارت کالا (${res.status}). در صورت خطای CORS، می‌توانید از پروکسی اختصاصی استفاده کنید.`);
  }

  const json = await res.json();
  const pc = json?.data?.price_chart || [];
  const history = (pc.length > 0 && pc[0].history) ? pc[0].history : (pc.length > 0 && pc[pc.length - 1].history ? pc[pc.length - 1].history : []);

  if (!history || history.length === 0) {
    throw new Error('تاریخچه قیمتی برای این کالا در دیجی‌کالا یافت نشد.');
  }

  const lastPoint = history[history.length - 1];
  const sellingPrice = lastPoint.selling_price || 0;
  const rrpPrice = lastPoint.rrp_price || sellingPrice;
  const discountPercent = rrpPrice > sellingPrice ? Math.round((1 - sellingPrice / rrpPrice) * 100) : 0;

  const analysis = analyzeDiscountClient(sellingPrice, rrpPrice, discountPercent, history);

  return {
    product_id: productId,
    title: `کالای کد ${productId}`,
    selling_price: sellingPrice,
    rrp_price: rrpPrice,
    analysis,
    history,
  };
}

// Utility to parse Digikala URL or ID
export function extractProductId(input: string): number | null {
  if (!input) return null;
  const clean = input.trim();
  // e.g. 4545846
  if (/^\d+$/.test(clean)) {
    return parseInt(clean, 10);
  }
  // e.g. /product/dkp-4545846/... or https://www.digikala.com/product/dkp-4545846/...
  const match = clean.match(/dkp-(\d+)/i) || clean.match(/\/product\/(\d+)/i) || clean.match(/product.*?(\d{5,})/i);
  if (match) {
    return parseInt(match[1], 10);
  }
  return null;
}
