import { OffersDataResponse, ProductChartData } from '../types';
import { analyzeDiscountClient } from './dealAnalyzer';

export interface ProxyPreset {
  id: string;
  name: string;
  url: string;
  description: string;
}

export const DEFAULT_PROXIES: ProxyPreset[] = [
  {
    id: 'allorigins',
    name: 'پروکسی عمومی AllOrigins (پیش‌فرض)',
    url: 'https://api.allorigins.win/raw?url=',
    description: 'سرویس عمومی و رایگان برای دور زدن محدودیت CORS در مرورگر',
  },
  {
    id: 'corsproxy',
    name: 'پروکسی عمومی CorsProxy.io',
    url: 'https://corsproxy.io/?url=',
    description: 'سرویس سریع و پایدار برای ارسال درخواست‌ها به دیجی‌کالا',
  },
  {
    id: 'direct',
    name: 'اتصال مستقیم (بدون پروکسی)',
    url: '',
    description: 'اتصال مستقیم بدون واسطه - مناسب محیط‌های محلی یا افزونه‌های CORS',
  },
];

export const PROXY_STORAGE_KEY = 'digicheck_proxy_url';

export function getStoredProxyUrl(): string {
  const saved = localStorage.getItem(PROXY_STORAGE_KEY);
  if (saved !== null) {
    return saved;
  }
  return DEFAULT_PROXIES[0].url;
}

export function setStoredProxyUrl(url: string): void {
  localStorage.setItem(PROXY_STORAGE_KEY, url.trim());
}

export function buildProxyUrl(targetUrl: string, proxyUrl?: string): string {
  const p = (proxyUrl !== undefined ? proxyUrl : getStoredProxyUrl()).trim();
  if (!p) {
    return targetUrl;
  }
  if (p.includes('?url=') || p.endsWith('?url=')) {
    return `${p}${encodeURIComponent(targetUrl)}`;
  }
  if (p.endsWith('?')) {
    return `${p}${encodeURIComponent(targetUrl)}`;
  }
  if (p.includes('?')) {
    return `${p}&url=${encodeURIComponent(targetUrl)}`;
  }
  return `${p.replace(/\/$/, '')}/${encodeURIComponent(targetUrl)}`;
}

export async function testProxyConnection(proxyUrl: string): Promise<{ success: boolean; latencyMs: number; error?: string }> {
  const startTime = Date.now();
  const testTargetUrl = 'https://api.digikala.com/v1/product/4545846/price-chart/';
  const fullUrl = buildProxyUrl(testTargetUrl, proxyUrl);

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 9000);

    const res = await fetch(fullUrl, {
      signal: controller.signal,
      headers: {
        'Accept': 'application/json',
      }
    });

    clearTimeout(timeoutId);
    const latencyMs = Date.now() - startTime;

    if (!res.ok) {
      return {
        success: false,
        latencyMs,
        error: `پاسخ با کد خطای ${res.status} دریافت شد`,
      };
    }

    const data = await res.json();
    if (data?.data?.price_chart || data?.status === 200) {
      return {
        success: true,
        latencyMs,
      };
    }

    return {
      success: true,
      latencyMs,
    };
  } catch (err: any) {
    const latencyMs = Date.now() - startTime;
    return {
      success: false,
      latencyMs,
      error: err.name === 'AbortError' ? 'مهلت زمان درخواست به پایان رسید (Timeout)' : (err.message || 'خطا در اتصال به پروکسی'),
    };
  }
}

// Load the pre-aggregated offers data generated by the crawler
export async function fetchOffersData(): Promise<OffersDataResponse> {
  const base = import.meta.env.BASE_URL || './';
  const response = await fetch(`${base}data/offers.json?t=${Date.now()}`);
  if (!response.ok) {
    throw new Error(`خطا در بارگذاری اطلاعات: ${response.status}`);
  }
  return await response.json();
}

// Load individual chart data from static JSON cache
export async function fetchCachedProductChart(productId: number): Promise<ProductChartData | null> {
  try {
    const base = import.meta.env.BASE_URL || './';
    const response = await fetch(`${base}data/charts/${productId}.json`);
    if (response.ok) {
      return await response.json();
    }
  } catch (err) {
    console.warn(`Chart not cached for ${productId}:`, err);
  }
  return null;
}

// Live manual check for ANY product entered by user
export async function fetchLiveProductChart(
  productId: number,
  proxyUrl?: string,
  bypassCache: boolean = false
): Promise<ProductChartData> {
  // First check if already in static cache (unless bypassed for live refresh)
  if (!bypassCache) {
    const cached = await fetchCachedProductChart(productId);
    if (cached) {
      return cached;
    }
  }

  // Live fetching via proxy
  const targetUrl = `https://api.digikala.com/v1/product/${productId}/price-chart/`;
  const fetchUrl = buildProxyUrl(targetUrl, proxyUrl);

  const res = await fetch(fetchUrl, {
    headers: {
      'Accept': 'application/json',
    },
  });

  if (!res.ok) {
    throw new Error(`خطا در استعلام چارت کالا (${res.status}). در صورت خطای CORS می‌توانید از تنظیمات، پروکسی اختصاصی یا پیش‌فرض دیگری انتخاب کنید.`);
  }

  const json = await res.json();
  const pc = json?.data?.price_chart || [];
  const history = (pc.length > 0 && pc[0].history) ? pc[0].history : (pc.length > 0 && pc[pc.length - 1].history ? pc[pc.length - 1].history : []);

  if (!history || history.length === 0) {
    throw new Error('تاریخچه قیمتی برای این کالا در دیجی‌کالا یافت نشد.');
  }

  const lastPoint = history[history.length - 1];
  const sellingPrice = lastPoint.selling_price || 0;
  const rrpPrice = lastPoint.rrp_price || sellingPrice;
  const discountPercent = rrpPrice > sellingPrice ? Math.round((1 - sellingPrice / rrpPrice) * 100) : 0;

  const analysis = analyzeDiscountClient(sellingPrice, rrpPrice, discountPercent, history);

  return {
    product_id: productId,
    title: `کالای کد ${productId}`,
    selling_price: sellingPrice,
    rrp_price: rrpPrice,
    analysis,
    history,
  };
}

// Utility to parse Digikala URL or ID
export function extractProductId(input: string): number | null {
  if (!input) return null;
  const clean = input.trim();
  // e.g. 4545846
  if (/^\d+$/.test(clean)) {
    return parseInt(clean, 10);
  }
  // e.g. /product/dkp-4545846/... or https://www.digikala.com/product/dkp-4545846/...
  const match = clean.match(/dkp-(\d+)/i) || clean.match(/\/product\/(\d+)/i) || clean.match(/product.*?(\d{5,})/i);
  if (match) {
    return parseInt(match[1], 10);
  }
  return null;
}
