import { OffersDataResponse, ProductChartData, PriceChartHistoryPoint, ProductItem } from '../types';
import { analyzeDiscountClient } from './dealAnalyzer';

export interface ProxyPreset {
  id: string;
  name: string;
  url: string;
  description: string;
}

export const DEFAULT_PROXIES: ProxyPreset[] = [
  {
    id: 'direct',
    name: 'اتصال مستقیم (بدون پروکسی)',
    url: '',
    description: 'اتصال مستقیم بدون واسطه - مناسب محیط‌های محلی یا زمان فعال بودن افزونه CORS',
  },
];

export const PROXY_STORAGE_KEY = 'digicheck_proxy_url';

export function getStoredProxyUrl(): string {
  const saved = localStorage.getItem(PROXY_STORAGE_KEY);
  if (saved !== null) {
    return saved;
  }
  // Default to empty (user enters their Cloudflare Worker URL)
  return '';
}

export function setStoredProxyUrl(url: string): void {
  localStorage.setItem(PROXY_STORAGE_KEY, url.trim());
}

export function buildProxyUrl(targetUrl: string, proxyUrl?: string): string {
  const p = (proxyUrl !== undefined ? proxyUrl : getStoredProxyUrl()).trim();
  if (!p) {
    return targetUrl;
  }
  if (p.includes('{url}')) {
    return p.replace('{url}', encodeURIComponent(targetUrl));
  }
  if (p.includes('?url=') || p.endsWith('?url=')) {
    return `${p}${encodeURIComponent(targetUrl)}`;
  }
  if (p.includes('?quest=') || p.endsWith('?quest=')) {
    return `${p}${encodeURIComponent(targetUrl)}`;
  }
  if (p.endsWith('?')) {
    return `${p}${encodeURIComponent(targetUrl)}`;
  }
  if (p.includes('?')) {
    return `${p}&url=${encodeURIComponent(targetUrl)}`;
  }
  return `${p.replace(/\/$/, '')}/${encodeURIComponent(targetUrl)}`;
}

export async function testProxyConnection(proxyUrl: string): Promise<{ success: boolean; latencyMs: number; error?: string }> {
  const startTime = Date.now();
  const testTargetUrl = 'https://api.digikala.com/v1/product/4545846/price-chart/';
  const fullUrl = buildProxyUrl(testTargetUrl, proxyUrl);

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 9000);

    const res = await fetch(fullUrl, {
      signal: controller.signal,
      headers: {
        'Accept': 'application/json',
      }
    });

    clearTimeout(timeoutId);
    const latencyMs = Date.now() - startTime;

    if (!res.ok) {
      let detail = `پاسخ با کد خطای ${res.status} دریافت شد`;
      if (res.status === 401) {
        detail = 'خطای ۴۰۱: این پروکسی عمومی نیاز به کلید API پولی دارد. لطفاً از ورکر شخصی کلودفلر (۱۰۰٪ رایگان) استفاده کنید.';
      } else if (res.status === 403) {
        detail = 'خطای ۴۰۳: دسترسی از طریق این سرور مسدود شده است.';
      } else if (res.status >= 500) {
        detail = `خطای ${res.status}: سرور پروکسی با اختلال یا تایم‌اوت مواجه شد.`;
      }
      return {
        success: false,
        latencyMs,
        error: detail,
      };
    }

    const data = await res.json();
    if (data?.data?.price_chart || data?.status === 200) {
      return {
        success: true,
        latencyMs,
      };
    }

    return {
      success: true,
      latencyMs,
    };
  } catch (err: any) {
    const latencyMs = Date.now() - startTime;
    return {
      success: false,
      latencyMs,
      error: err.name === 'AbortError' ? 'مهلت زمان درخواست به پایان رسید (Timeout)' : (err.message || 'خطا در اتصال به پروکسی'),
    };
  }
}

// Load the pre-aggregated offers data generated by the crawler (bundled / action cache)
export async function fetchOffersData(): Promise<OffersDataResponse> {
  const base = import.meta.env.BASE_URL || './';
  const response = await fetch(`${base}data/offers.json?t=${Date.now()}`);
  if (!response.ok) {
    throw new Error(`خطا در بارگذاری اطلاعات: ${response.status}`);
  }
  return await response.json();
}

// Load individual chart data from static JSON cache (backup)
export async function fetchCachedProductChart(productId: number): Promise<ProductChartData | null> {
  try {
    const base = import.meta.env.BASE_URL || './';
    const response = await fetch(`${base}data/charts/${productId}.json?t=${Date.now()}`);
    if (response.ok) {
      const data = await response.json();
      return {
        ...data,
        is_live: false,
      };
    }
  } catch (err) {
    console.warn(`Chart not cached for ${productId}:`, err);
  }
  return null;
}

/**
 * Directly calls Digikala price-chart API through candidate proxies.
 * Resilient multi-proxy strategy matching chandchandi.
 */
export async function fetchLiveProductChartDirect(
  productId: number,
  proxyUrl?: string
): Promise<ProductChartData> {
  const targetUrl = `https://api.digikala.com/v1/product/${productId}/price-chart/`;
  
  // Build proxy candidates list:
  const activeProxy = proxyUrl !== undefined ? proxyUrl.trim() : getStoredProxyUrl().trim();
  const candidateProxies: string[] = [];

  if (activeProxy) {
    candidateProxies.push(activeProxy);
  }

  // Add default public fallbacks matching chandchandi
  const commonFallbacks = [
    '', // Direct
    'https://api.allorigins.win/raw?url=',
    'https://api.codetabs.com/v1/proxy?quest=',
  ];
  for (const fb of commonFallbacks) {
    if (!candidateProxies.includes(fb)) {
      candidateProxies.push(fb);
    }
  }

  let lastError: any = null;

  for (const pUrl of candidateProxies) {
    const fetchUrl = buildProxyUrl(targetUrl, pUrl);
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 6500);

      const res = await fetch(fetchUrl, {
        signal: controller.signal,
        headers: {
          'Accept': 'application/json',
        },
      });
      clearTimeout(timeoutId);

      if (!res.ok) {
        lastError = new Error(`پروکسی با کد ${res.status} پاسخ داد`);
        continue;
      }

      const json = await res.json();
      const pc = json?.data?.price_chart || [];
      let history: PriceChartHistoryPoint[] = [];

      if (Array.isArray(pc)) {
        for (const item of pc) {
          if (Array.isArray(item.history) && item.history.length > 0) {
            history = item.history;
            break;
          }
        }
      }

      if (!history || history.length === 0) {
        throw new Error('تاریخچه قیمتی برای این کالا در دیجی‌کالا یافت نشد.');
      }

      const lastPoint = history[history.length - 1];
      const sellingPrice = lastPoint.selling_price || 0;
      const rrpPrice = lastPoint.rrp_price || sellingPrice;
      const discountPercent = rrpPrice > sellingPrice ? Math.round((1 - sellingPrice / rrpPrice) * 100) : 0;

      const analysis = analyzeDiscountClient(sellingPrice, rrpPrice, discountPercent, history);

      return {
        product_id: productId,
        title: `کالای کد ${productId}`,
        selling_price: sellingPrice,
        rrp_price: rrpPrice,
        analysis,
        history,
        is_live: true,
      };
    } catch (err: any) {
      lastError = err;
    }
  }

  throw lastError || new Error('خطا در استعلام چارت کالا از طریق پروکسی');
}

export interface FetchChartResult {
  data: ProductChartData;
  source: 'live' | 'cache';
  latencyMs?: number;
}

/**
 * Primary chart fetching function for the app:
 * 1. Tries LIVE fetch via proxy first (ensures real-time data directly from Digikala API)
 * 2. If live proxy fails, falls back to static cache from GitHub Action
 */
export async function fetchProductChartWithFallback(
  productId: number,
  proxyUrl?: string,
  preferLive: boolean = true
): Promise<FetchChartResult> {
  const startTime = Date.now();

  if (preferLive) {
    try {
      const liveData = await fetchLiveProductChartDirect(productId, proxyUrl);
      return {
        data: liveData,
        source: 'live',
        latencyMs: Date.now() - startTime,
      };
    } catch (liveErr) {
      console.warn(`[DigiCheck] Live chart fetch failed for ${productId}, falling back to cache:`, liveErr);
    }
  }

  // Fallback to cached chart
  const cachedData = await fetchCachedProductChart(productId);
  if (cachedData && cachedData.history && cachedData.history.length > 0) {
    return {
      data: cachedData,
      source: 'cache',
      latencyMs: Date.now() - startTime,
    };
  }

  // If live wasn't tried yet, try live now
  if (!preferLive) {
    try {
      const liveData = await fetchLiveProductChartDirect(productId, proxyUrl);
      return {
        data: liveData,
        source: 'live',
        latencyMs: Date.now() - startTime,
      };
    } catch (liveErr) {
      console.warn(`[DigiCheck] Live fallback failed for ${productId}:`, liveErr);
    }
  }

  throw new Error('چارت این کالا در دیجی‌کالا یا کش یافت نشد. لطفاً در تنظیمات (آیکون سرور) پروکسی یا ورکر کلودفلر شخصی خود را بررسی کنید.');
}

// Backward-compatible alias for manual checker / components
export async function fetchLiveProductChart(
  productId: number,
  proxyUrl?: string
): Promise<ProductChartData> {
  const result = await fetchProductChartWithFallback(productId, proxyUrl, true);
  return result.data;
}

/**
 * Live fetch for the entire Incredible Offers dataset directly from Digikala API
 */
export async function fetchLiveOffers(proxyUrl?: string): Promise<OffersDataResponse> {
  const targetUrl = 'https://api.digikala.com/v1/incredible-offers/';
  const activeProxy = proxyUrl !== undefined ? proxyUrl : getStoredProxyUrl();
  const fetchUrl = buildProxyUrl(targetUrl, activeProxy);

  const res = await fetch(fetchUrl, {
    headers: {
      'Accept': 'application/json',
    },
  });

  if (!res.ok) {
    throw new Error(`خطا در دریافت زنده شگفت‌انگیزها (${res.status})`);
  }

  const json = await res.json();
  const rawData = json?.data || {};

  const OFFER_KEYS: Record<string, { title: string; badge: string; icon: string }> = {
    'incredible_products_list': { title: 'شگفت‌انگیز روز', badge: 'عمومی', icon: 'Sparkles' },
    'lightening_deal_products': { title: 'پیشنهاد صاعقه‌ای', badge: 'تخفیف ویژه', icon: 'Zap' },
    'running_out_incredible_products': { title: 'فرصت پایانی', badge: 'در حال اتمام', icon: 'Flame' },
    'fresh_incredible_products': { title: 'شگفت‌انگیز سوپرمارکتی', badge: 'تندمصرف (FMCG)', icon: 'ShoppingBag' },
    'digiplus_incredible_products': { title: 'شگفت‌انگیز دیجی‌پلاس', badge: 'دیجی‌پلاس', icon: 'Eye' },
  };

  const offerCategories: Record<string, any> = {};
  let totalCount = 0;
  const stats = {
    real_deals_count: 0,
    fake_deals_count: 0,
    neutral_deals_count: 0,
    great_deals_count: 0,
    max_discount: 0,
  };

  for (const [key, meta] of Object.entries(OFFER_KEYS)) {
    const catData = rawData[key] || {};
    const rawProducts = Array.isArray(catData.products) ? catData.products : [];

    const products: ProductItem[] = rawProducts.map((p: any) => {
      const pid = p.id;
      const priceInfo = p.default_variant?.price || {};
      const selling = priceInfo.selling_price || 0;
      const rrp = priceInfo.rrp_price || selling;
      const discount = priceInfo.discount_percent || 0;
      if (discount > stats.max_discount) stats.max_discount = discount;

      const images = p.images || {};
      const mainImg = Array.isArray(images.main?.url) && images.main.url.length > 0
        ? images.main.url[0]
        : (typeof images.main?.url === 'string' ? images.main.url : '');

      const catTitle = p.data_layer?.item_category2 || p.category?.title || 'سایر';
      const catId = p.category?.id || null;
      const uri = p.url?.uri || `/product/dkp-${pid}/`;

      return {
        id: pid,
        title_fa: p.title_fa || '',
        title_en: p.title_en || '',
        image: mainImg,
        selling_price: selling,
        rrp_price: rrp,
        discount_percent: discount,
        rating: p.rating?.rate || 0,
        rating_count: p.rating?.count || 0,
        category_id: catId,
        category_title: catTitle,
        url: `https://www.digikala.com${uri}`,
        offer_type: key,
        offer_type_title: meta.title,
        has_chart: false,
        analysis: null,
      };
    });

    totalCount += products.length;
    offerCategories[key] = {
      key,
      title: meta.title,
      badge: meta.badge,
      icon: meta.icon,
      count: products.length,
      products,
    };
  }

  const now = new Date();
  const timePart = now.toLocaleTimeString('fa-IR', { hour: '2-digit', minute: '2-digit' });
  const datePart = now.toLocaleDateString('fa-IR');

  return {
    last_updated: now.toISOString(),
    last_updated_fa: `${timePart} (${datePart}) - زنده`,
    total_products: totalCount,
    stats,
    main_categories: rawData.main_categories || [],
    offer_categories: offerCategories,
  };
}

// Utility to parse Digikala URL or ID
export function extractProductId(input: string): number | null {
  if (!input) return null;
  const clean = input.trim();
  // e.g. 4545846
  if (/^\d+$/.test(clean)) {
    return parseInt(clean, 10);
  }
  // e.g. /product/dkp-4545846/... or https://www.digikala.com/product/dkp-4545846/...
  const match = clean.match(/dkp-(\d+)/i) || clean.match(/\/product\/(\d+)/i) || clean.match(/product.*?(\d{5,})/i);
  if (match) {
    return parseInt(match[1], 10);
  }
  return null;
}
